config/routes.rb
Rails.application.routes.draw do
  root "dashboards#show"

  devise_for :users

  resources :tasks
  resources :categories
  resources :dashboards, only: :show do
    collection do
      patch :categories_reorder
      patch :tasks_reorder
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :dashboard

  has_many :tasks, dependent: :destroy

  scope :populated_category_tasks, -> { joins(:tasks).distinct }

  acts_as_list sequential_updates: false, scope: :dashboard

  validates :name, presence: true, uniqueness: true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user

  has_many :categories
end

app/models/task.rb
class Task < ApplicationRecord
  STATUSES = {
    created: 0,
    in_progress: 1,
    pending: 2,
    completed: 3
  }.freeze

  enum status: STATUSES

  belongs_to :user
  belongs_to :category, optional: true

  scope :categorized, -> { where.not(category_id: nil) }
  scope :uncategorized, -> { where(category_id: nil) }

  acts_as_list scope: [:category_id, :user_id]

  after_create { self.move_to_top }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :dashboard

  has_many :tasks

  after_create -> { create_dashboard }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %w[show edit update destroy]
  before_action :find_prev_category, only: :create

  def index
    @categories = current_user.dashboard.categories
  end

  def show
    @tasks = @category.tasks
  end

  def new
    prev_position = Category.find(params[:prevCategoryId]).position
    @category = current_user.dashboard.categories.new(position: prev_position + 1)

    respond_to { | format | format.turbo_stream }
  end

  def create
    @category = current_user.dashboard.categories.new(category_params)

    respond_to { | format | format.turbo_stream if @category.save }
  end

  def edit
    render :new
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.turbo_stream
      else
        format.json { render json: @category.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to categories_path, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  def find_prev_category
    @prev_category = current_user.dashboard.categories.find_by(position: params[:category][:position].to_i - 1)
  end

  def category_params
    params.require(:category).permit(:name, :position)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    set_instance_variables
  end

  def categories_reorder
    category = current_user.dashboard.categories.find_by(position: params[:old_position])
    category.insert_at(params[:new_position])
    set_instance_variables

    head :ok
  end

  def tasks_reorder
    from_category, to_category = set_categories
    task                       = current_user.tasks.find_by(category: from_category, position: params[:old_position])
    task.update(category: to_category) unless params[:from].eql?(params[:to])
    task.insert_at(params[:new_position])
    set_instance_variables

    head :ok
  end

  private

  def set_instance_variables
    @categories = current_user.dashboard.categories.order(position: :asc)
    @tasks      = current_user.tasks.uncategorized.order(position: :asc)
  end

  def set_categories
    from = params[:from].eql?('nil') ? nil : params[:from]
    to   = params[:to].eql?('nil') ? nil : Category.find(params[:to])

    [from, to]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %w[edit update destroy]
  before_action :set_category, only: :new

  def index
    @categories = current_user.dashboard.categories.populated_category_tasks
    @tasks = current_user.tasks
  end

  def show
    @task = Task.find(params[:id])
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.update('task-content', partial: 'categories/task_details', locals: { task: @task }) }
    end
  end

  def edit
    render :new
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.turbo_stream
      end
    end
  end

  def new
    @task = Task.new

    respond_to { | format | format.turbo_stream }
  end

  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.turbo_stream
        format.html { redirect_to task_url(@task), notice: 'Task was successfully created.' }
      end
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to tasks_path, notice: 'Task was successfully destroyed.' }
    end
  end

  private

  def set_category
    @category_id = params[:categoryId] && Category.find(params[:categoryId]).id
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<%= turbo_frame_tag dom_id(category), data: { controller: 'category task',
                                              category_name: category.name,
                                              category_url_value: category_path(category),
                                              category_category_id_value: category.id } do %>
  <div class="card category-card item" style="width: 350px;">
    <h5 class="card-header mh-55">
      <div id='categoryName' class="d-flex align-items-center justify-content-between">
        <span data-category-target="name">
          <%= category.name %>
        </span>
        <div class="controls d-flex align-items-center no-drug">
          <button class="btn" type='button' data-action="task#create">
            <i class="fa-solid fa-plus"></i>
          </button>
          <div class="dropdown ms-2" data-category-target="dropdown">
            <button class="btn category-menu" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa-solid fa-ellipsis"></i>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a href="#" data-action="category#create:prevent" class="dropdown-item">Create</a>
              <a href="#" data-action="category#showInput:prevent" class="dropdown-item">Rename</a>
              <a href="#" data-action="category#destroy:prevent" class="dropdown-item">Delete</a>
            </div>
          </div>
        </div>
      </div>
    </h5>
    <div class="card-body no-drug">
      <ul class="p-0 d-flex flex-column gap-3" data-category-id="<%= category.id %>" data-sortable-target="tasks">
        <% category.tasks.order(position: :asc).each do |task| %>
          <%= render 'categories/task_preview', task: task, category_id: category.id %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/categories/_form.html.erb
<div class='card category-card item' style='min-width: 350px;'>
  <h5 class='card-header mh-55'>
    <div id='categoryName' class='d-flex align-items-center justify-content-between'>
      <%= simple_form_for category, defaults: { input_html: { class: 'mt-1' } } do |f| %>
        <%= f.input_field :name, label: false %>
        <%= f.hidden_field :position, value: category.position %>
      <% end %>
      <button class='btn remove-category' type='button'>
        <i class='fa-solid fa-xmark'></i>
      </button>
    </div>
  </h5>
  <div class='card-body no-drug'>
  </div>
</div>

app/views/categories/_new_category.html.erb
<%= link_to 'Create category', new_category_path %>

app/views/categories/_task_details.html.erb
<div class="task-details-container h-100" data-controller="task" data-task-url-value="<%= task_path(task) %>">
  <h4 class="task-title" data-action="click->task#edit"><%= task.title %></h4>
  <button class="close-button" id="close-details" data-action="task#close">&times;</button>
  <p class="task-description" data-action="click->task#edit"><%= task.description %></p>
  <p class="task-meta">Due Date: <%= task.due_date %></p>
  <p class="task-meta">Status: <%= task.status %></p>
</div>

app/views/categories/_task_preview.html.erb
<li class="list-unstyled task-item" data-controller="task"
                                    data-task-id="<%= task.id %>"
                                    data-action="click->task#show"
                                    data-task-url-value="<%= task_path(task) %>">
  <div class="card">
    <div class="card-body">
      <p class="card-text text-wrap">
        <span class="title"><%= task.title %></span>
        <i class="bi bi-arrows-move task-handle pr-3 ms-1"></i>
      </p>
    </div>
  </div>
</li>

app/views/categories/_uncategorized_tasks.html.erb
<%= turbo_frame_tag 'uncategorized', data: { controller: 'task' } do %>
  <div class="card category-card item" style="width: 350px;">
    <h5 class="card-header mh-55 d-flex align-items-center">
      Uncategorized
      <button class="btn" type='button' data-action="task#create">
        <i class="fa-solid fa-plus"></i>
      </button>
    </h5>
    <div class="card-body" data-controller="sortable" data-sortable-target="categories">
      <ul class="p-0 d-flex flex-column gap-3" data-category-id="nil" data-sortable-target="tasks">
        <% @tasks.each do |task| %>
          <%= render 'categories/task_preview', task: task, category_id: nil %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/categories/create.turbo_stream.erb
<%= turbo_stream.replace('new_category', partial: 'categories/category', locals: { category: @category }) %>

app/views/categories/destroy.turbo_stream.erb
<%= turbo_stream.remove(@category) %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div id="categories">
  <%= render @categories %>
</div>

<%= turbo_frame_tag 'new_category' do %>
  <%= render 'categories/new_category' %>
<% end %>

app/views/categories/new.html.erb
<%= render 'categories/form' %>

app/views/categories/new.turbo_stream.erb
<%= turbo_stream.append(@category, partial: 'categories/form', locals: { category: @category }) %>

app/views/categories/reorder.turbo_stream.erb
<%= turbo_stream.update('categories', partial: 'categories/categories', locals: { categories: @categories }) %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  <strong>Tasks:</strong>
  <%- @tasks.each do |task| %>
    <%= render 'tasks/task', task: task %>
  <% end %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %>
<%= button_to 'Delete', @category, method: :delete %>

app/views/categories/update.turbo_stream.erb
<%= turbo_stream.replace(@category, partial: 'categories/category', locals: { category: @category }) %>

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>

<div id='categories' class='d-flex gap-3 x-overflow-scrolling'>
  <%= render 'categories/uncategorized_tasks' %>
  <div id='namedCategories' class='d-flex gap-3' data-controller='sortable' data-sortable-target='categories'>
    <% @categories.each do |category| %>
      <%= render 'categories/category', category: category %>
    <% end %>
  </div>
</div>
<div id="task-content" data-controller="task"></div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- Logo (Link to root_path) -->
    <a class="navbar-brand" href="/">Your Logo</a>

    <div class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Dropdown
      </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="<%= categories_path %>">Categories</a></li>
        <li><a class="dropdown-item" href="<%= tasks_path %>">Tasks</a></li>
      </ul>
    </div>

    <!-- Toggler Button for mobile view -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <!-- Sign-in Buttons -->
        <%- if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, class: 'nav-link btn btn-primary me-2', data: { turbo_method: 'delete' } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link btn btn-primary me-2' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link btn btn-outline-primary' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="csrf-token" content="<%= form_authenticity_token %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= turbo_frame_tag @task do %>
  <%= simple_form_for @task, data: { controller: 'selects' } do |f| %>
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :due_date, start_year: Date.today.year, input_html: { class: 'form-control' } %>
    <%= f.input :category_id, collection: current_user.categories %>

    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to 'Back', tasks_path %>
  <% end %>
<% end %>

app/views/tasks/_new_task.html.erb
<div class="card">
  <div class="card-body">
    <%= simple_form_for task, html: { class: 'd-flex align-items-center justify-content-between' }, defaults: { wrapper: false } do |f| %>
      <%= f.input :title, label: false, autocomplete: false, wrapper_html: { class: 'mb-0' } %>
      <%= f.hidden_field :category_id, value: category %>
      <button class='btn remove-task' type='button'>
        <i class='fa-solid fa-xmark'></i>
      </button>
    <% end %>
  </div>
</div>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag dom_id(task) do %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= task.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted">Until - <%= task.due_date %></h6>
      <p class="card-text"><%= task.description %></p>
      <%= link_to 'Edit', edit_task_path(task) %>
      <%= button_to 'Delete', task, method: :delete %>
    </div>
  </div>
<% end %>

app/views/tasks/_tasks.html.erb
<% @tasks.each do |task| %>
  <%= render task %>
<% end %>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.replace('new_task', partial: 'categories/task_preview', locals: { task: @task }) %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.remove(@task) %>

app/views/tasks/index.html.erb
<h1>Dashboard</h1>

<div class="d-flex gap-3" data-controller="sortable" data-sortable-target="categories">
  <% @categories.each do |cat| %>
    <div class="card category-card item" style="min-width: 350px;">
      <h5 class="card-header">
        <%= cat.name %>
        <i class="bi bi-arrows-move category-handle float-end"></i>
      </h5>
      <div class="card-body">
        <ul class="p-0" data-category-id="<%= cat.id %>" data-sortable-target="tasks">
          <%- current_user.tasks.category_tasks(cat.id).each do |t| %>
            <li class="task-item list-unstyled" data-task-id="<%= t.id %>">
              <i class="bi bi-arrows-move task-handle pr-3"></i>
              <%= t.title %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>








<!--<div id="tasks">-->
  <%#= render 'tasks/tasks' %>
<!--</div>-->

<%#= turbo_frame_tag 'new_task' do %>
  <%#= render 'tasks/new_task' %>
<%# end %>

app/views/tasks/new.html.erb
<%= simple_form_for @task, data: { controller: 'selects' } do |f| %>
  <%= f.input :title, input_html: { class: 'form-control' } %>
<% end %>

app/views/tasks/new.turbo_stream.erb
<%= turbo_stream.update(@task, partial: 'tasks/new_task', locals: { task: @task, category: @category_id }) %>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.update(@task, partial: 'tasks/task', locals: { task: @task }) %>